# comments

#Target : dependency
#<TAB>Command

PROJECT_NAME = all.exe
SRC = init.c add.c view.c search.c update.c bookCount.c main.c
$(PROJECT_NAME): $(SRC)
	gcc $(SRC) -o all.exe
	
run: $(PROJECT_NAME)
	$(PROJECT_NAME)