# comments

#Target : dependency
#<TAB>Command

PROJECT_NAME = all.exe
SRC = main.c add.c search.c view.c update.c bookCount.c
$(PROJECT_NAME): $(SRC)
	gcc $(SRC) -o all.exe
	
run: $(PROJECT_NAME)
	$(PROJECT_NAME)